name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: kelseyhightower/kubernetes-the-hard-way@v2.0
        with:
          token: ${{ secrets.PAT }}
          owner: bachato
          base: master
          head: master
